### ISSUE TITLE
Build failure for integrating sdk 0.5.9 , with gms:google-services lib

### ISSUE THREAD

**Issue by arafath** [cleverpush/cleverpush-android-sdk#1]
I am getting build failure when trying to integration your sdk version 0.5.9 within my project, where I also have to integrate "google gms library" with version , ""com.google.gms:google-services:4.3.3

Error message is as below : ========================================
In project 'XYX' a resolved Google Play services library dependency depends on another at an exact version (e.g. "
[10.2.1, 17.3.99]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

Dependency failing: com.cleverpush:cleverpush:0.5.9 -> com.google.firebase:firebase-messaging@[10.2.1, 17.3.99], but fir
ebase-messaging version was 17.3.4.

The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
ifact with the issue.
-- Project 'XYZ' depends onto com.google.firebase:firebase-messaging@{strictly 17.3.4}
-- Project 'XYZ' depends onto com.cleverpush:cleverpush@0.5.9
-- Project 'XYZ' depends onto com.cleverpush:cleverpush@{strictly 0.5.9}

For extended debugging info execute Gradle from the command line with ./gradlew --info :BNNePaper:assembleDebug to see t
he dependency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at ht
tps://github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to 
your build.gradle file.

**Comment by gbhrdt** [comment]
Should be resolved with the new 1.0.0 release
