### ISSUE TITLE
CleverPush.getAvailableTopics() not working and crashing

### ISSUE THREAD

**Issue by avlaev** [cleverpush/cleverpush-android-sdk#3]
Background:
I am testing with the newest version the library - implementation ('com.cleverpush:cleverpush:1.6.6')

1. I am trying to get the topics list with child and parent dependencies between topics.
2. I am using the CleverPush.getAvailableTopics() method to get the list

Expected Result:
To get a non empty list with topics. (Keep in mind that we do have the list of topics setup)

Actual Result:
I get an empty list with topics.

I debugged the sdk and it seems that the bug is in method:
`Cleverpush.getAvailableTopicsFromConfig()`

on this line

`ChannelTopic topic = new ChannelTopic(topicObject.getString("_id"), topicObject.getString("name"), topicObject.getString("parentTopic"));`

more precisely the part
`topicObject.getString("parentTopic")`  - not every topic element has the "parentTopic" key so this makes it an optional parameter. The result is that this line crashes the whole parsing of the topics with Exception

`org.json.JSONException: No value for parentTopic`

 Please fix it.
Note that CleverPush.showTopicsDialog() works fine and displays the topics so the issue is not related to setup or missing data bur rather to parsing inside the library.

**Comment by gbhrdt** [comment]
Hi @avlaev  thank you very much for your bug report and the detailed description.
This has been fixed in version `1.6.7` which has just been pushed to Maven. Non-existing parent topic IDs will now be `null`.
