### ISSUE TITLE
Build failure for integrating sdk 1.27.3

### ISSUE THREAD

**Issue by emakovski** [cleverpush/cleverpush-android-sdk#96]
Hi, I'm getting failure trying to implement CleverPush SDK 1.27.3.
In our project we use google-services:4.3.15 and firebase-bom:31.2.0 implementation as well.
Please have a look at error message:

In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[10.2.
1, 23.0.99]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

Dependency failing: com.cleverpush:cleverpush:1.27.3 -> com.google.firebase:firebase-messaging@[10.2.1, 23.0.99], but fi
rebase-messaging version was 23.1.1.

The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
ifact with the issue.
-- Project 'app' depends onto com.cleverpush:cleverpush@[1.27.3]
-- Project 'app' depends onto com.cleverpush:cleverpush@1.27.3
-- Project 'app' depends onto com.google.firebase:firebase-messaging@[23.1.1]
-- Project 'app' depends onto com.google.firebase:firebase-bom@31.2.0
-- Project 'app' depends onto com.google.firebase:firebase-bom@[31.2.0]

For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = true }" to your bu
ild.gradle file.

**Comment by gbhrdt** [comment]
Hi @emakovski 
You can add the following line at the bottom of app/build.gradle to resolve the issue:

```
googleServices { disableVersionCheck = true }
```

**Comment by emakovski** [comment]
Thanks @gbhrdt.
It works now. But what will be its side effects?

**Comment by gbhrdt** [comment]
@emakovski Nothing should break here. It's basically a [known bug](https://github.com/invertase/react-native-firebase/issues/1676) in the Google Services Gradle plugin.
